export type MoveKey =
  | "breathe-arms"
  | "hold-pose"
  | "tap-seated"
  | "cat-cow"
  | "stretch-neck"
  | "stretch-side"
  | "march"
  | "walk"
  | "tiptoe"
  | "one-leg"
  | "dance"
  | "clap"
  | "carry";

export const MOVE_KEYS: readonly MoveKey[] = [
  "breathe-arms",
  "hold-pose",
  "tap-seated",
  "cat-cow",
  "stretch-neck",
  "stretch-side",
  "march",
  "walk",
  "tiptoe",
  "one-leg",
  "dance",
  "clap",
  "carry",
] as const;

export type JointAngles = {
  neck?: number;
  torso?: number;
  torsoY?: number;
  leftShoulder?: number;
  rightShoulder?: number;
  leftElbow?: number;
  rightElbow?: number;
  leftHip?: number;
  rightHip?: number;
  leftKnee?: number;
  rightKnee?: number;
};

export type PostureType = "standing" | "seated" | "quadruped";

export type MoveDefinition = {
  key: MoveKey;
  cycleSeconds: number;
  posture: PostureType;
  poses: JointAngles[];
};

export const MOVE_DEFINITIONS: Record<MoveKey, MoveDefinition> = {
  "breathe-arms": {
    key: "breathe-arms",
    cycleSeconds: 3.6,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: 0,
        leftShoulder: -12,
        rightShoulder: 12,
        leftElbow: -6,
        rightElbow: 6,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: -6,
        torso: 0,
        leftShoulder: -68,
        rightShoulder: 68,
        leftElbow: -22,
        rightElbow: 22,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  "hold-pose": {
    key: "hold-pose",
    cycleSeconds: 3.2,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: -2,
        leftShoulder: -32,
        rightShoulder: 32,
        leftElbow: -42,
        rightElbow: 42,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 2,
        leftShoulder: -32,
        rightShoulder: 32,
        leftElbow: -42,
        rightElbow: 42,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  "tap-seated": {
    key: "tap-seated",
    cycleSeconds: 3.0,
    posture: "seated",
    poses: [
      {
        neck: 0,
        torso: 0,
        leftShoulder: -10,
        rightShoulder: 10,
        leftElbow: -40,
        rightElbow: 40,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 18,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -10,
        rightShoulder: 10,
        leftElbow: -40,
        rightElbow: 40,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 18,
      },
    ],
  },
  "cat-cow": {
    key: "cat-cow",
    cycleSeconds: 3.6,
    posture: "quadruped",
    poses: [
      {
        neck: -14,
        torso: 6,
        leftShoulder: 0,
        rightShoulder: 0,
        leftElbow: 0,
        rightElbow: 0,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 16,
        torso: -8,
        leftShoulder: 0,
        rightShoulder: 0,
        leftElbow: 0,
        rightElbow: 0,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  "stretch-neck": {
    key: "stretch-neck",
    cycleSeconds: 3.5,
    posture: "standing",
    poses: [
      {
        neck: -20,
        torso: 0,
        leftShoulder: -10,
        rightShoulder: 10,
        leftElbow: -5,
        rightElbow: 5,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -10,
        rightShoulder: 10,
        leftElbow: -5,
        rightElbow: 5,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 20,
        torso: 0,
        leftShoulder: -10,
        rightShoulder: 10,
        leftElbow: -5,
        rightElbow: 5,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  "stretch-side": {
    key: "stretch-side",
    cycleSeconds: 3.6,
    posture: "standing",
    poses: [
      {
        neck: -8,
        torso: -10,
        leftShoulder: -10,
        rightShoulder: 135,
        leftElbow: -5,
        rightElbow: 20,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -10,
        rightShoulder: 10,
        leftElbow: -5,
        rightElbow: 5,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 8,
        torso: 10,
        leftShoulder: -135,
        rightShoulder: 10,
        leftElbow: -20,
        rightElbow: 5,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  march: {
    key: "march",
    cycleSeconds: 3.2,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: 0,
        leftShoulder: 16,
        rightShoulder: -24,
        leftElbow: -16,
        rightElbow: 38,
        leftHip: -24,
        rightHip: 0,
        leftKnee: 34,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -6,
        rightShoulder: 6,
        leftElbow: -8,
        rightElbow: 8,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -24,
        rightShoulder: 16,
        leftElbow: -38,
        rightElbow: 16,
        leftHip: 0,
        rightHip: -24,
        leftKnee: 0,
        rightKnee: 34,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -6,
        rightShoulder: 6,
        leftElbow: -8,
        rightElbow: 8,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  walk: {
    key: "walk",
    cycleSeconds: 3.0,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: 0,
        leftShoulder: 12,
        rightShoulder: -16,
        leftElbow: -10,
        rightElbow: 18,
        leftHip: -16,
        rightHip: 12,
        leftKnee: 10,
        rightKnee: 6,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -5,
        rightShoulder: 5,
        leftElbow: -6,
        rightElbow: 6,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -16,
        rightShoulder: 12,
        leftElbow: -18,
        rightElbow: 10,
        leftHip: 12,
        rightHip: -16,
        leftKnee: 6,
        rightKnee: 10,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -5,
        rightShoulder: 5,
        leftElbow: -6,
        rightElbow: 6,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  tiptoe: {
    key: "tiptoe",
    cycleSeconds: 3.2,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: 0,
        torsoY: 0,
        leftShoulder: -12,
        rightShoulder: 12,
        leftElbow: -6,
        rightElbow: 6,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: -3,
        torso: 0,
        torsoY: -10,
        leftShoulder: -28,
        rightShoulder: 28,
        leftElbow: -12,
        rightElbow: 12,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  "one-leg": {
    key: "one-leg",
    cycleSeconds: 3.4,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: -2,
        leftShoulder: -48,
        rightShoulder: 48,
        leftElbow: -16,
        rightElbow: 16,
        leftHip: 0,
        rightHip: 16,
        leftKnee: 0,
        rightKnee: 48,
      },
      {
        neck: 0,
        torso: 2,
        leftShoulder: -52,
        rightShoulder: 44,
        leftElbow: -16,
        rightElbow: 16,
        leftHip: 0,
        rightHip: 16,
        leftKnee: 0,
        rightKnee: 48,
      },
    ],
  },
  dance: {
    key: "dance",
    cycleSeconds: 3.2,
    posture: "standing",
    poses: [
      {
        neck: 6,
        torso: -7,
        leftShoulder: -42,
        rightShoulder: -18,
        leftElbow: -28,
        rightElbow: -24,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 14,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -15,
        rightShoulder: 15,
        leftElbow: -10,
        rightElbow: 10,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: -6,
        torso: 7,
        leftShoulder: 18,
        rightShoulder: 42,
        leftElbow: 24,
        rightElbow: 28,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 14,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -15,
        rightShoulder: 15,
        leftElbow: -10,
        rightElbow: 10,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  clap: {
    key: "clap",
    cycleSeconds: 3.0,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: 0,
        leftShoulder: 34,
        rightShoulder: -34,
        leftElbow: -58,
        rightElbow: 58,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 0,
        leftShoulder: -22,
        rightShoulder: 22,
        leftElbow: -28,
        rightElbow: 28,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
  carry: {
    key: "carry",
    cycleSeconds: 3.2,
    posture: "standing",
    poses: [
      {
        neck: 0,
        torso: -3,
        leftShoulder: -14,
        rightShoulder: 14,
        leftElbow: -52,
        rightElbow: 52,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
      {
        neck: 0,
        torso: 3,
        leftShoulder: -14,
        rightShoulder: 14,
        leftElbow: -52,
        rightElbow: 52,
        leftHip: 0,
        rightHip: 0,
        leftKnee: 0,
        rightKnee: 0,
      },
    ],
  },
};
