// The QR link between the parent app and the child app. See docs/proposals/SPLIT_APPS_AND_QR_LINK.md.
// Pure types: no React, no storage. Everything here travels between two phones through a camera,
// so every payload is validated before it is trusted (schemas.ts).

import type { CheckIn, DateKey, MissionLog } from "@/types";

export const LINK_VERSION = 1 as const;

/** Prefix of a pairing code (parent to child). Plain text: it carries the key, never health data. */
export const PAIRING_PREFIX = "CCP1:";
/** Prefix of a data frame (child to parent). Always encrypted with the family key. */
export const SHARE_PREFIX = "CCD1:";

/**
 * A reward the parents defined at home ("Choose today's dinner"). Label and price only.
 * Same fields as `SpecialReward` in the economy state, so the two map 1:1.
 */
export type LinkSpecialReward = {
  id: string;
  label: string;
  /** Fire the child spends to light it, 1 to 100. Never depends on what the child answered. */
  fireCost: number;
};

/**
 * The child asked for a reward from home. A request the parents confirm, never a promise.
 * The child device only ever creates "requested"; "done" is set on the parent device and is never
 * overwritten by a later share (merge adds unknown ids, never replaces known ones).
 */
export type LinkRewardClaim = {
  id: string;
  rewardId: string;
  /** Local day on the child device. */
  date: DateKey;
  status: "requested" | "done";
  doneDate?: DateKey;
};

/**
 * Parent to child. Shown once at home. Contains the family key, so it must never contain health data
 * and must never be shown anywhere else than on the parent's screen.
 */
export type PairingPayload = {
  v: typeof LINK_VERSION;
  familyId: string;
  /** 16 random bytes, base64url. Generated by the parent app, never typed by anyone. */
  keyB64: string;
  nickname: string;
  allowedMissionIds: string[];
  specialRewards: LinkSpecialReward[];
  createdAt: string;
};

/** Child to parent. Encrypted with the family key. A delta of the chosen range, merged idempotently. */
export type SharePayload = {
  v: typeof LINK_VERSION;
  familyId: string;
  from: DateKey;
  to: DateKey;
  checkIns: CheckIn[];
  missionLogs: MissionLog[];
  rewardClaims: LinkRewardClaim[];
};

/** The slice of a state that `mergeShare` reads and writes. */
export type ShareMergeTarget = {
  checkIns: CheckIn[];
  missionLogs: MissionLog[];
  rewardClaims: LinkRewardClaim[];
};

export type MergeSummary = {
  checkInsAdded: number;
  checkInsReplaced: number;
  missionLogsAdded: number;
  rewardClaimsAdded: number;
};

export type LinkErrorCode =
  /** The text is not one of our codes at all. */
  | "not-a-code"
  /** A code from a newer or older version of the app. */
  | "wrong-version"
  /** The frame set is not complete yet. */
  | "incomplete"
  /** Decryption failed: another family's code, or a damaged scan. */
  | "wrong-family"
  /** The code decoded but its content is not what we expect. */
  | "corrupt";

export class LinkError extends Error {
  readonly code: LinkErrorCode;

  constructor(code: LinkErrorCode, message: string) {
    super(message);
    this.name = "LinkError";
    this.code = code;
  }
}
